# Generated by Django 5.2.16 on 2026-07-31 17:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('min_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('max_amount', models.DecimalField(decimal_places=2, default=500000.0, max_digits=12)),
                ('required_role', models.CharField(default='PROCUREMENT_MANAGER', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grn_number', models.CharField(max_length=50, unique=True)),
                ('received_date', models.DateField(auto_now_add=True)),
                ('inspection_status', models.CharField(choices=[('PASSED', 'Passed Quality Inspection'), ('PARTIAL_REJECT', 'Partial Rejection'), ('FAILED', 'Failed Inspection')], default='PASSED', max_length=20)),
                ('received_items', models.JSONField(default=list, help_text='List of inspected line items: [{ item_name, qty_ordered, qty_received, qty_accepted, notes }]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('matching_status', models.CharField(choices=[('MATCHED', '3-Way Matched (PO + GRN + Invoice)'), ('DISCREPANCY_PRICE', 'Price Discrepancy Flagged'), ('DISCREPANCY_QTY', 'Quantity Discrepancy Flagged'), ('UNMATCHED', 'Pending Inspection Matching')], default='MATCHED', max_length=30)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goods_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='procurement.goodsreceipt')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='vendors.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('annual_budget', models.DecimalField(decimal_places=2, default=10000000.0, max_digits=14)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='procurement.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_number', models.CharField(max_length=50, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'NEFT / RTGS Bank Transfer'), ('ACH', 'ACH Direct Deposit'), ('WIRE', 'Wire Transfer'), ('CHEQUE', 'Cheque')], default='BANK_TRANSFER', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('COMPLETED', 'Payment Cleared'), ('FAILED', 'Payment Failed')], default='COMPLETED', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='procurement.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('po_number', models.CharField(max_length=50, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued to Vendor'), ('ACKNOWLEDGED', 'Vendor Acknowledged'), ('IN_TRANSIT', 'In Transit / Shipped'), ('DELIVERED', 'Delivered & Inspected'), ('COMPLETED', 'Completed & Paid'), ('CANCELLED', 'Cancelled')], default='ISSUED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='vendors.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='procurement.purchaseorder'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipts', to='procurement.purchaseorder'),
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('total_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('required_by_date', models.DateField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_MANAGER', 'Pending Manager Approval'), ('PENDING_FINANCE', 'Pending Finance Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RFQ_CREATED', 'RFQ Created')], default='PENDING_MANAGER', max_length=30)),
                ('items_legacy', models.JSONField(blank=True, default=list, help_text='Legacy JSON item list')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='vendors.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='procurement.department')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DELEGATED', 'Delegated')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='procurement.purchaserequest')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequestItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('unit_of_measure', models.CharField(default='Units', max_length=30)),
                ('target_unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('specifications', models.TextField(blank=True)),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='procurement.purchaserequest')),
            ],
        ),
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rfq_number', models.CharField(max_length=50, unique=True)),
                ('submission_deadline', models.DateTimeField()),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published / Open'), ('EVALUATED', 'AI Evaluated'), ('AWARDED', 'Awarded'), ('CLOSED', 'Closed')], default='PUBLISHED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqs', to='procurement.purchaserequest')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='rfq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='procurement.rfq'),
        ),
        migrations.CreateModel(
            name='VendorInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('VIEWED', 'Viewed RFQ'), ('RESPONDED', 'Quotation Submitted'), ('DECLINED', 'Declined Bid'), ('EXPIRED', 'Expired')], default='INVITED', max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.rfq')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
            options={
                'unique_together': {('rfq', 'vendor')},
            },
        ),
        migrations.AddField(
            model_name='rfq',
            name='invited_vendors',
            field=models.ManyToManyField(related_name='rfqs_invited', through='procurement.VendorInvitation', to='vendors.vendor'),
        ),
    ]
