# Generated by Django 5.2.16 on 2026-07-31 16:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('items', models.JSONField(help_text='Structured item list: [{ item_name, quantity, spec, est_unit_price }]')),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('required_by_date', models.DateField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RFQ_CREATED', 'RFQ Created')], default='PENDING_APPROVAL', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='vendors.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rfq_number', models.CharField(max_length=50, unique=True)),
                ('submission_deadline', models.DateTimeField()),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published / Open'), ('EVALUATED', 'AI Evaluated'), ('AWARDED', 'Awarded'), ('CLOSED', 'Closed')], default='PUBLISHED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_vendors', models.ManyToManyField(related_name='rfqs_invited', to='vendors.vendor')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqs', to='procurement.purchaserequest')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('po_number', models.CharField(max_length=50, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued to Vendor'), ('ACKNOWLEDGED', 'Vendor Acknowledged'), ('IN_TRANSIT', 'In Transit / Shipped'), ('DELIVERED', 'Delivered & Inspected'), ('COMPLETED', 'Completed & Paid'), ('CANCELLED', 'Cancelled')], default='ISSUED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='vendors.vendor')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='procurement.rfq')),
            ],
        ),
    ]
