# Generated by Django 5.2.16 on 2026-07-31 18:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
        ('vendors', '0002_vendor_organization_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='procurement.organization'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='procurement.organization'),
        ),
        migrations.AddField(
            model_name='rfq',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfqs', to='procurement.organization'),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='received_items',
            field=models.JSONField(default=list, help_text='List of inspected line items'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('COMPLETED', 'Payment Cleared'), ('FAILED', 'Failed')], default='COMPLETED', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_MANAGER', 'Pending Manager Approval'), ('PENDING_FINANCE', 'Pending Finance Approval'), ('PENDING_CIO', 'Pending CIO Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RFQ_CREATED', 'RFQ Created')], default='PENDING_MANAGER', max_length=30),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('APPROVAL_REQUIRED', 'Approval Required'), ('RFQ_BID_DISPATCHED', 'RFQ Bid Dispatched'), ('GRN_INSPECTION', 'GRN Inspection'), ('CONTRACT_EXPIRING', 'Contract Expiring Soon'), ('PRICE_ANOMALY', 'Price Anomaly Alert')], default='APPROVAL_REQUIRED', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(default='/', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='procurement.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=150)),
                ('min_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('max_amount', models.DecimalField(decimal_places=2, default=10000000.0, max_digits=12)),
                ('approval_chain', models.JSONField(default=list, help_text="Ordered list of required roles e.g. ['DEPARTMENT_HEAD', 'FINANCE', 'CIO']")),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.category')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.department')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_rules', to='procurement.organization')),
            ],
        ),
    ]
