# Generated by Django 5.2.16 on 2026-07-31 22:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_purchaseorder_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prefix', models.CharField(max_length=20)),
                ('year', models.IntegerField(default=2026)),
                ('last_number', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='procurement.organization')),
            ],
            options={
                'unique_together': {('prefix', 'year', 'organization')},
            },
        ),
    ]
