# Generated by Django 5.2.16 on 2026-07-31 17:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=30)),
                ('tax_id', models.CharField(blank=True, help_text='GST / VAT / Tax ID', max_length=50)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(default='Mumbai', max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('rating', models.DecimalField(decimal_places=2, default=4.5, max_digits=3)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active / Qualified'), ('SUSPENDED', 'Suspended'), ('BLACKLISTED', 'Blacklisted')], default='ACTIVE', max_length=20)),
                ('is_preferred', models.BooleanField(default=False, help_text='Preferred supplier for fast-track RFQs')),
                ('on_time_delivery_rate', models.DecimalField(decimal_places=2, default=95.0, help_text='On-time delivery percentage', max_digits=5)),
                ('quality_score', models.DecimalField(decimal_places=2, default=96.5, help_text='Inspected quality pass rate percentage', max_digits=5)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], default='LOW', max_length=20)),
                ('certifications', models.JSONField(blank=True, default=list, help_text="List of certifications e.g. ['ISO 9001', 'SOC2', 'GMP']")),
                ('bank_details_encrypted', models.JSONField(blank=True, default=dict, help_text='Secure bank account & IFSC / IBAN details')),
                ('ai_performance_score', models.JSONField(blank=True, default=dict, help_text='Stores AI vendor scoring breakdown')),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='vendors', to='vendors.category')),
            ],
        ),
    ]
