# Generated by Django 5.2.16 on 2026-07-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='organization_name',
            field=models.CharField(default='Apex Global Procurement', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='ai_performance_score',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='bank_details_encrypted',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='certifications',
            field=models.JSONField(blank=True, default=list, help_text='List of certifications'),
        ),
    ]
