# Generated by Django 5.2.16 on 2026-07-31 22:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendor_organization_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPerformanceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_name', models.CharField(help_text='e.g. 2026-Q1 or 2026-07', max_length=50)),
                ('on_time_delivery_rate', models.DecimalField(decimal_places=2, default=95.0, max_digits=5)),
                ('quality_pass_rate', models.DecimalField(decimal_places=2, default=96.5, max_digits=5)),
                ('price_competitiveness_score', models.DecimalField(decimal_places=2, default=90.0, max_digits=5)),
                ('discrepancy_rate', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('total_orders_fulfilled', models.IntegerField(default=0)),
                ('total_spend_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('ai_risk_assessment', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_snapshots', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-period_name'],
                'unique_together': {('vendor', 'period_name')},
            },
        ),
    ]
