# Generated by Django 5.2.16 on 2026-07-31 17:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procurement', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.FileField(blank=True, null=True, upload_to='quotations/')),
                ('raw_text', models.TextField(blank=True, help_text='Extracted text from PDF OCR')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('delivery_days', models.IntegerField(default=5, help_text='Delivery lead time in calendar days')),
                ('warranty_months', models.IntegerField(default=12)),
                ('payment_terms', models.CharField(default='Net 30 Days', max_length=255)),
                ('ocr_status', models.CharField(choices=[('PENDING', 'Pending AI Extraction'), ('SUCCESS', 'AI Extraction Complete'), ('FAILED', 'OCR Failed')], default='SUCCESS', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='procurement.rfq')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='vendors.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=18.0, help_text='GST / Tax rate percentage', max_digits=5)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='quotations.quotation')),
                ('request_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_items', to='procurement.purchaserequestitem')),
            ],
        ),
    ]
