# Generated by Django 5.2.16 on 2026-07-31 16:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procurement', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.FileField(blank=True, null=True, upload_to='quotations/%Y/%m/')),
                ('total_quoted_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('delivery_lead_time_days', models.IntegerField(default=7, help_text='Delivery timeframe in days')),
                ('warranty_months', models.IntegerField(default=12, help_text='Warranty period in months')),
                ('payment_terms', models.CharField(default='30% Advance, 70% Delivery', max_length=255)),
                ('extracted_data', models.JSONField(blank=True, default=dict, help_text='Parsed line items, unit costs, tax rates')),
                ('ocr_status', models.CharField(choices=[('PENDING', 'Pending Extraction'), ('PROCESSING', 'Processing OCR/AI'), ('COMPLETED', 'Extraction Complete'), ('FAILED', 'Extraction Failed')], default='COMPLETED', max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='procurement.rfq')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='vendors.vendor')),
            ],
        ),
    ]
