# Generated by Django 5.2.16 on 2026-07-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='organization_name',
            field=models.CharField(default='Apex Global Procurement', max_length=255),
        ),
        migrations.AlterField(
            model_name='contract',
            name='ai_analysis',
            field=models.JSONField(blank=True, default=dict, help_text='AI contract assessment'),
        ),
    ]
